// Clé: funciona sem internet depois da primeira abertura (gerado por prototipo/montar.mjs)
const VERSAO = "cle-v1.15.0-971294934c";
const ARQUIVOS = ["./imagens/interesses/aventura-radical.webp?v=252b5dec","./imagens/interesses/bem-estar.webp?v=6b68497b","./imagens/interesses/carros-e-estradas-cenicas.webp?v=502a7fbc","./imagens/interesses/cidades.webp?v=a5c28a61","./imagens/interesses/compras.webp?v=613104d8","./imagens/interesses/cultura-local.webp?v=fe4a02d5","./imagens/interesses/esportes.webp?v=21ae379d","./imagens/interesses/fotografia.webp?v=70f63544","./imagens/interesses/gastronomia.webp?v=26ea4b54","./imagens/interesses/museus-e-historia.webp?v=78e46128","./imagens/interesses/natureza-e-ar-livre.webp?v=9373725f","./imagens/interesses/parques-tematicos.webp?v=0cf31327","./imagens/interesses/praia.webp?v=28101939","./imagens/interesses/shows-e-musica.webp?v=68e7758f","./imagens/interesses/trilhas.webp?v=4595374a","./imagens/interesses/vida-noturna.webp?v=8bcee2a3","./imagens/situacoes/chuva-1.webp?v=7552c682","./imagens/situacoes/chuva-2.webp?v=3aacd200","./imagens/situacoes/chuva-3.webp?v=2bd9ff5f","./imagens/situacoes/chuva-4.webp?v=fae77221","./imagens/situacoes/estrada-1.webp?v=d3d8e830","./imagens/situacoes/estrada-2.webp?v=06783924","./imagens/situacoes/estrada-3.webp?v=7a75e557","./imagens/situacoes/estrada-4.webp?v=09a4c0dd","./imagens/situacoes/fila-1.webp?v=cb7f74b6","./imagens/situacoes/fila-2.webp?v=6395d005","./imagens/situacoes/fila-3.webp?v=51a5ab9f","./imagens/situacoes/fila-4.webp?v=6b0ad1fd","./imagens/situacoes/hotel-1.webp?v=f02527ff","./imagens/situacoes/hotel-2.webp?v=3b10385e","./imagens/situacoes/hotel-3.webp?v=2caf0005","./imagens/situacoes/hotel-4.webp?v=e87669d8","./imagens/situacoes/jantar-1.webp?v=93e1542a","./imagens/situacoes/jantar-2.webp?v=165054a4","./imagens/situacoes/jantar-3.webp?v=4232e5cc","./imagens/situacoes/jantar-4.webp?v=321d1ed4","./imagens/situacoes/mirante-1.webp?v=4fa47734","./imagens/situacoes/mirante-2.webp?v=106fd93d","./imagens/situacoes/mirante-3.webp?v=f5cf36fb","./imagens/situacoes/mirante-4.webp?v=1244e356","./imagens/situacoes/parque-1.webp?v=f9036fd3","./imagens/situacoes/parque-2.webp?v=ccecb5dd","./imagens/situacoes/parque-3.webp?v=7ce0d85d","./imagens/situacoes/parque-4.webp?v=ec0752ef","./","./index.html","./manifest.webmanifest","./icon-192.png","./icon-512.png","./icon-maskable-512.png","./carteira/lib/qrcode.js","./carteira/lib/jsQR.js","./carteira/icon-192.png"];
const FONTES = /^https:\/\/fonts\.(googleapis|gstatic)\.com\//;
// o GitHub Pages manda o navegador guardar cada arquivo por 10 min: a versão nova é baixada direto do servidor
// (cache: "reload"), senão o app avisaria "versão nova" e continuaria mostrando a antiga (bug de 01/10/2026)
self.addEventListener("install", (e) => { e.waitUntil(caches.open(VERSAO).then((c) => c.addAll(ARQUIVOS.map((u) => new Request(u, { cache: "reload" })))).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== VERSAO && !k.startsWith("cle-voz-")).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (e) => {
  const r = e.request;
  if (r.method !== "GET") return;
  if (r.mode === "navigate") { e.respondWith(fetch(r.url, { cache: "no-cache", credentials: "same-origin" }).then((resp) => { const cp = resp.clone(); caches.open(VERSAO).then((c) => c.put("./index.html", cp)); return resp; }).catch(() => caches.match("./index.html"))); return; }
  if (FONTES.test(r.url)) { e.respondWith(caches.match(r).then((m) => m || fetch(r).then((resp) => { const cp = resp.clone(); caches.open(VERSAO).then((c) => c.put(r, cp)); return resp; }))); return; }
  if (new URL(r.url).origin === location.origin) e.respondWith(caches.match(r).then((m) => m || fetch(r)));
});
